export const strings = {
    TITLE_EDIT_DB : "Edit",
    TITLE_ADD_DB : "Add an expense",
    EXPENSE_ADDED: "Expense Added",
    EXPENSE_UPDATED : "Expense updated",
    CURRENCY: "Currency",
    ADD : "Add",
    DONE : "Done", 
    SELECT_ACCOUNT: "Select an account",
    ERROR_IMG_SIZE_EXCEED: "Image size can not be more than 3MB",
    ERROR_NO_USER: "No user found",
    ERROR_UNAUTORISED: "Unauthorized: No token found",
    ERROR_ACCOUNT_NAME_EXISTS: "Account with this name already exists",
    ERROR_IMAGE_UPLOAD: "Error while uploading image",
    ERROR_REQUIRED_FIELDS: "Fill all the required fields",
    ERROR_FETCHING_TRANSACTIONS: "There is some error while fetching transactions.",
    WARNING_EMPTY_INPUT: " can not be empty",
    TOOLTIP_DELETE_TRANSACTION: "Delete",
    TOOLTIP_EDIT_TRANSACTION: "Edit",
    TOOLTIP_DOWNLOAD_IMAGE: "Download attached image", 
    MSG_WALLET_REQUIRED: "Expense can not be added without a wallet.",
}